version: '3.8'

services:
  bot:
    build: .
    container_name: job-scraper-bot
    # This tells Docker to always restart the bot (e.g. when you turn on your laptop)
    restart: unless-stopped
    ipc: host
    deploy:
      resources:
        limits:
          memory: 400M
    volumes:
      # Map the cache so we don't spam notifications on restart
      - ./cache.json:/app/cache.json
      # Map config so you can change settings without rebuilding the container
      - ./config.json:/app/config.json
    environment:
      - TARGET_URL=https://apps.mep.go.cr/formulario?shem=rimspwouoe
